# Generated by Django 5.1.7 on 2025-11-01 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Game name (e.g., '8-Ball Pool', 'Table Tennis', 'PS4 Console 1')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the game/activity')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of players (1 for PC, 4 for pool table)')),
                ('booking_type', models.CharField(choices=[('SINGLE', 'Single Booking (Private Only)'), ('HYBRID', 'Hybrid Booking (Private + Shared)')], help_text='Single (private only) or Hybrid (private + shared)', max_length=10)),
                ('opening_time', models.TimeField(help_text='Daily opening time (e.g., 11:00 AM)')),
                ('closing_time', models.TimeField(help_text='Daily closing time (e.g., 11:00 PM)')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of each slot in minutes')),
                ('available_days', models.JSONField(default=list, help_text="List of available weekdays ['monday', 'tuesday', ...]")),
                ('private_price', models.DecimalField(decimal_places=2, help_text='Price for private booking (full capacity)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('shared_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per spot for shared booking (only for hybrid games)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the game is available for booking')),
                ('image', models.ImageField(blank=True, help_text='Game photo', null=True, upload_to='games/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GamingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for the gaming station', max_length=50, unique=True)),
                ('station_type', models.CharField(choices=[('PC', 'Gaming PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X'), ('SWITCH', 'Nintendo Switch'), ('VR', 'VR Gaming Setup')], help_text='Type of gaming station', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the gaming station')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the station is available for booking')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Whether the station is under maintenance')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications like CPU, GPU, RAM, etc.')),
                ('image', models.ImageField(blank=True, help_text='Station photo', null=True, upload_to='stations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gaming Station (DEPRECATED)',
                'verbose_name_plural': 'Gaming Stations (DEPRECATED)',
                'ordering': ['station_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('PRIVATE', 'Private Booking (Full Capacity)'), ('SHARED', 'Shared Booking (Individual Spots)')], default='PRIVATE', help_text='Private (full capacity) or Shared (individual spots)', max_length=10)),
                ('spots_booked', models.PositiveIntegerField(blank=True, help_text='Number of spots booked (1-capacity for shared, full capacity for private)', null=True)),
                ('price_per_spot', models.DecimalField(blank=True, decimal_places=2, help_text='Price per spot at time of booking', max_digits=8, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the booking (price_per_spot * spots_booked)', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('payment_status', models.CharField(blank=True, help_text='Payment status from gateway', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the booking')),
                ('start_time', models.DateTimeField(blank=True, help_text='DEPRECATED: Use game_slot instead', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='DEPRECATED: Use game_slot instead', null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use price_per_spot instead', max_digits=6, null=True)),
                ('is_walk_in', models.BooleanField(default=False, help_text='DEPRECATED: Online-only bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='authentication.customer')),
                ('game', models.ForeignKey(blank=True, help_text='Game being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.game')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GameSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_custom', models.BooleanField(default=False, help_text='True for manually added slots')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.game')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('game', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='game_slot',
            field=models.ForeignKey(blank=True, help_text='Specific time slot being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.gameslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gaming_station',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use game field instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.gamingstation'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.PositiveIntegerField()),
                ('booked_spots', models.PositiveIntegerField(default=0)),
                ('is_private_booked', models.BooleanField(default=False)),
                ('game_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='booking.gameslot')),
            ],
            options={
                'verbose_name': 'Slot Availability',
                'verbose_name_plural': 'Slot Availabilities',
            },
        ),
    ]
