# Generated by Django 5.1.7 on 2025-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay payment signature', max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID (DEPRECATED)', max_length=100),
        ),
    ]
