# Generated by Django 5.1.7 on 2025-11-03 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_razorpay_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether booking has been verified by scanning QR code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code for booking verification', null=True, upload_to='booking_qr_codes/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for QR code verification', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was verified', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Owner/staff who verified the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
