# Generated by Django 5.1.7 on 2025-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_qr_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform fee charged for this booking', max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal (price_per_spot * spots_booked) before platform fee', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the booking (subtotal + platform_fee)', max_digits=8, null=True),
        ),
    ]
