# Generated by Django 5.1.7 on 2025-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_platform_fee_to_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_notified',
            field=models.BooleanField(default=False, help_text='Whether owner has been notified via Telegram about this booking'),
        ),
    ]
