# Generated by Django 5.1.7 on 2025-11-03 10:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_owner_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Commission amount deducted from owner's share (7%)", max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount transferred to owner after commission deduction', max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_transfer_id',
            field=models.CharField(blank=True, help_text='Razorpay transfer ID for route payment to owner', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when transfer was processed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of transfer to owner account', max_length=20),
        ),
    ]
