# Generated by Django 5.2.8 on 2025-11-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_optimize_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reservation_expired',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the payment reservation has expired'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when payment reservation expires (5 minutes from booking creation)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Payment Expired')], default='PENDING', max_length=20),
        ),
    ]
