# Generated by Django 5.2.8 on 2025-11-07 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cafeowner_razorpay_account_email_and_more'),
        ('booking', '0008_booking_is_reservation_expired_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['game_slot', 'status'], name='booking_slot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'reservation_expires_at'], name='booking_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='booking_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['game', 'status'], name='booking_game_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gameslot',
            index=models.Index(fields=['game', 'date', 'is_active'], name='gameslot_game_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='gameslot',
            index=models.Index(fields=['date', 'start_time'], name='gameslot_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gameslot',
            index=models.Index(fields=['is_active', 'date'], name='gameslot_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='slotavailability',
            index=models.Index(fields=['game_slot'], name='slotavail_gameslot_idx'),
        ),
    ]
