# Generated by Django 5.2.8 on 2025-11-08 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cafeowner_razorpay_account_email_and_more'),
        ('booking', '0009_booking_booking_slot_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='booking_customer_created_idx'),
        ),
    ]
