# Generated by Django 5.2.8 on 2025-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_booking_customer_created_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='booking',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for QR code verification (dynamically generated, no file storage)', max_length=100),
        ),
    ]
