# Generated by Django 5.2.8 on 2025-11-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_qrverificationattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when verification token expires (24 hours after slot end)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts (security audit)'),
        ),
    ]
