# Generated by Django 5.1.7 on 2025-11-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapnexsuperuser',
            name='platform_fee_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount (₹)'), ('PERCENT', 'Percentage (%)')], default='PERCENT', help_text='Type of platform fee calculation', max_length=10),
        ),
        migrations.AlterField(
            model_name='tapnexsuperuser',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform fee - can be fixed amount or percentage based on platform_fee_type', max_digits=8),
        ),
    ]
