# Generated by Django 5.1.7 on 2025-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_platform_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapnexsuperuser',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Telegram Bot API Token from BotFather', max_length=200),
        ),
        migrations.AddField(
            model_name='tapnexsuperuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID (personal or group) to receive notifications', max_length=50),
        ),
        migrations.AddField(
            model_name='tapnexsuperuser',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable Telegram notifications'),
        ),
        migrations.AddField(
            model_name='tapnexsuperuser',
            name='telegram_notification_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Chat'), ('GROUP', 'Group Chat')], default='PERSONAL', help_text='Type of Telegram chat for notifications', max_length=10),
        ),
    ]
