# Generated by Django 5.1.7 on 2025-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tapnexsuperuser_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeowner',
            name='razorpay_account_email',
            field=models.EmailField(blank=True, help_text='Email associated with the Razorpay account', max_length=254),
        ),
        migrations.AddField(
            model_name='cafeowner',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text='Razorpay Account/Route ID for receiving payments (e.g., acc_xxxxx or route_xxxxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='cafeowner',
            name='razorpay_account_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', help_text='Status of Razorpay account', max_length=20),
        ),
    ]
