# Generated by Django 5.2.8 on 2025-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cafeowner_razorpay_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapnexsuperuser',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Commission percentage deducted from owner's share (e.g., 7.00 for 7%) - REQUIRED", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tapnexsuperuser',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee charged to customer - can be fixed amount or percentage based on platform_fee_type - REQUIRED', max_digits=8, null=True),
        ),
    ]
