# Generated by Django 5.1.7 on 2025-11-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_tapnexsuperuser_commission_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether staff member is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='authentication.cafeowner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cafe Staff',
                'verbose_name_plural': 'Cafe Staff',
            },
        ),
    ]
